/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import Util.ConnectionFactory;
import controlle.ProjectControlle;
import java.sql.Connection;
import model.Project;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
      Connection c = ConnectionFactory.getConnection();  
    
        
        ConnectionFactory.closeConnection(c);
        
           
      ProjectControlle projectcontrolle = new ProjectControlle();
       
       Project project = new Project();
       
       project.setName("Projeto Teste");
       project.setDescription("description");
       
       projectcontrolle.save(project);  
       
      
     //  project.setName("Novo nome do projeto");
     //  projectcontrolle.update(project);
       
    //  List<Project> projects = projectcontrolle.getAll();
      
        
        
      //  System.out.println("Total de projetos = "+ projects.size());
         
    }
}
