/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import Util.ConnectionFactory;
import controlle.ProjectControlle;
import controlle.TaskController;
import java.sql.Connection;
import java.util.Date;
import model.Project;
import model.Task;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
      Connection c = ConnectionFactory.getConnection();  
    
        
      ConnectionFactory.closeConnection(c);
        
           //SimpleDateFormat format= new SimpleDateFormat("dd/MM/YYYY");
         /* Date x;
          x= new Date();
        
      TaskController projectcontrolle = new TaskController();
       
       Task project = new Task();
       
       project.setName("TesteTask");
       project.setDescription("description");
       project.setNotes("Nem tudo que reluz é ouro!");
       project.setIsCompleted(true);
       project.setDeadline(x);
       project.setCreatedAt(x);
       project.setUpdateAt(x);
       project.setIdProject(5);
       
       projectcontrolle.save(project); */
     
    }
}

 