/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import Util.ConnectionFactory;
import java.sql.Connection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
      Connection c = ConnectionFactory.getConnection();  
    
        
        ConnectionFactory.closeConnection(c);
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}
